---
- file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700

- openssh_keypair:
   path: "{{ ansible_env.HOME }}/.ssh/helper_rsa"
   size: 4096
   comment: "{{ ansible_env.USER }}@helper"
   state: present

- blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: present
    backup: yes
    create: yes
    marker: "# {mark} {{ item.name }}-{{ item.clusterid }} MANAGED BLOCK"
    block: |
      Host {{ item.name }}-{{ item.clusterid }}
        HostName %h.{{ item.clusterid }}.{{ dns.domain }}
        User core
        IdentityFile {{ ansible_env.HOME }}/.ssh/helper_rsa
      Host {{ item.name }}.{{ item.clusterid }}.{{ dns.domain }}
        User core
        IdentityFile {{ ansible_env.HOME }}/.ssh/helper_rsa
  loop: "{{ masters }}"

- blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: present
    backup: yes
    create: yes
    marker: "# {mark} {{ item.name }}-{{ item.clusterid }} MANAGED BLOCK"
    block: |
      Host {{ item.name }}-{{ item.clusterid }}
        HostName %h.{{ item.clusterid }}.{{ dns.domain }}
        User core
        IdentityFile {{ ansible_env.HOME }}/.ssh/helper_rsa
      Host {{ item.name }}.{{ item.clusterid }}.{{ dns.domain }}
        User core
        IdentityFile {{ ansible_env.HOME }}/.ssh/helper_rsa
  loop: "{{ workers }}"
  when:
    - workers is defined
    - workers | length > 0

- blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: present
    backup: yes
    create: yes
    marker: "# {mark} {{ item.name }}-{{ item.clusterid }} MANAGED BLOCK"
    block: |
      Host {{ item.name }}-{{ item.clusterid }}
        HostName %h.{{ item.clusterid }}.{{ dns.domain }}
        User core
        IdentityFile {{ ansible_env.HOME }}/.ssh/helper_rsa
      Host {{ item.name }}.{{ item.clusterid }}.{{ dns.domain }}
        User core
        IdentityFile {{ ansible_env.HOME }}/.ssh/helper_rsa
  loop: "{{ bootstrap }}"
