- name: Validate values for DNS compatibility
  fail:
    msg: "Please revise your vars.yaml file. Invalid characters found in hostnames"
  when: item is search('{{ chars }}')
  loop:
  - "{{ dns.domain }}"
  - "{{ helper.name }}"
  - "{{ bootstrap }}"
  - "{{ masters }}"
  - "{{ workers | default('') }}"
